package me.chipnesh.hardware.command

enum class Command {
    TOP_LEFT,
    BOTTOM_LEFT,
    TOP_RIGHT,
    BOTTOM_RIGHT,
    TOP_LEFT_TOP_RIGHT,
    TOP_LEFT_BOTTOM_RIGHT,
    BOTTOM_LEFT_TOP_RIGHT,
    BOTTOM_LEFT_BOTTOM_RIGHT,
    CENTRE,
    IGNORED;


    companion object {

        val WITH_TOP_LEFT = arrayOf(TOP_LEFT, TOP_LEFT_BOTTOM_RIGHT, TOP_LEFT_TOP_RIGHT)

        val WITH_BOTTOM_LEFT = arrayOf(BOTTOM_LEFT, BOTTOM_LEFT_BOTTOM_RIGHT, BOTTOM_LEFT_TOP_RIGHT)

        val WITH_TOP_RIGHT = arrayOf(TOP_RIGHT, TOP_LEFT_TOP_RIGHT, BOTTOM_LEFT_TOP_RIGHT)

        val WITH_BOTTOM_RIGHT = arrayOf(BOTTOM_RIGHT, TOP_LEFT_BOTTOM_RIGHT, BOTTOM_LEFT_BOTTOM_RIGHT)
    }
}
